### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sparta3407** [jxy-s/herpaderping#21]
hey when i try to build the solution using visual studio 2019 i get these errors :

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'wil/common.h': No such file or directory	ProcessHerpaderping	C:\Users\**\Desktop\jxy-s-herpaderping-3d4c5ff\source\ProcessHerpaderping\pch.hpp	46

**Comment by jxy-s** [comment]
Seems like you may not have pulled the submodules, try following the instructions again:
```
git clone https://github.com/jxy-s/herpaderping.git
cd .\herpaderping\
git submodule update --init --recursive
MSBuild .\herpaderping.sln
```
If the issue persists, then the VS solution include directories are broken in your local repo somehow.
