### ISSUE TITLE
unable to build with visual studio 2019

### ISSUE THREAD

**Issue by dstaulcu** [jxy-s/herpaderping#24]
Greetings!

I'm trying to build this project with visual studio 2019. 
The build fails with error:   "cannot open source file "span"
Any suggestions on where to find this library?

Thanks

**Comment by jxy-s** [comment]
Duplicate of https://github.com/jxy-s/herpaderping/issues/23. Make sure your compiler is up to date.

**Comment by dstaulcu** [comment]
indeed that was the problem.  had just downloaded and installed 2019 for this project.  thanks!
